"""File auto-generated by tglib TL generator. Do not edit manually."""
from ..tlobject import TLObject
from typing import Optional, List, Union
import os
import struct
from datetime import datetime


class AppConfig(TLObject):
    """TL type: help.appConfig"""
    CONSTRUCTOR_ID = 0xdd18782e
    SUBCLASS_OF_ID = 0x14381c9a

    def __init__(self, hash: int, config: 'TypeJSONValue'):
        self.hash = hash
        self.config = config

    def to_dict(self):
        return {
            '_': 'AppConfig',
            'hash': self.hash,
            'config': self.config,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', self.hash))
        buf.write(bytes(self.config))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_hash = reader.read_int()
        _args['hash'] = _val_hash
        _val_config = reader.tgread_object()
        _args['config'] = _val_config
        return cls(**_args)


class AppConfigNotModified(TLObject):
    """TL type: help.appConfigNotModified"""
    CONSTRUCTOR_ID = 0x7cde641d
    SUBCLASS_OF_ID = 0x14381c9a

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'AppConfigNotModified',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()


class CountriesList(TLObject):
    """TL type: help.countriesList"""
    CONSTRUCTOR_ID = 0x87d0759e
    SUBCLASS_OF_ID = 0xea31fe88

    def __init__(self, countries: List['TypeCountry'], hash: int):
        self.countries = countries
        self.hash = hash

    def to_dict(self):
        return {
            '_': 'CountriesList',
            'countries': self.countries,
            'hash': self.hash,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.countries)))
        for item in self.countries:
            buf.write(bytes(item))
        buf.write(struct.pack('<i', self.hash))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_countries = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_countries = []
        for _ in range(_count_countries):
            _item_countries = reader.tgread_object()
            _list_countries.append(_item_countries)
        _args['countries'] = _list_countries
        _val_hash = reader.read_int()
        _args['hash'] = _val_hash
        return cls(**_args)


class CountriesListNotModified(TLObject):
    """TL type: help.countriesListNotModified"""
    CONSTRUCTOR_ID = 0x93cc1f32
    SUBCLASS_OF_ID = 0xea31fe88

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'CountriesListNotModified',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()


class DeepLinkInfoEmpty(TLObject):
    """TL type: help.deepLinkInfoEmpty"""
    CONSTRUCTOR_ID = 0x66afa166
    SUBCLASS_OF_ID = 0x984aac38

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'DeepLinkInfoEmpty',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()


class InviteText(TLObject):
    """TL type: help.inviteText"""
    CONSTRUCTOR_ID = 0x18cb9f78
    SUBCLASS_OF_ID = 0xcf70aa35

    def __init__(self, message: str):
        self.message = message

    def to_dict(self):
        return {
            '_': 'InviteText',
            'message': self.message,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.message))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_message = reader.tgread_string()
        _args['message'] = _val_message
        return cls(**_args)


class NoAppUpdate(TLObject):
    """TL type: help.noAppUpdate"""
    CONSTRUCTOR_ID = 0xc45a6536
    SUBCLASS_OF_ID = 0x5897069e

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'NoAppUpdate',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()


class PassportConfig(TLObject):
    """TL type: help.passportConfig"""
    CONSTRUCTOR_ID = 0xa098d6af
    SUBCLASS_OF_ID = 0xc666c0ad

    def __init__(self, hash: int, countries_langs: 'TypeDataJSON'):
        self.hash = hash
        self.countries_langs = countries_langs

    def to_dict(self):
        return {
            '_': 'PassportConfig',
            'hash': self.hash,
            'countries_langs': self.countries_langs,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', self.hash))
        buf.write(bytes(self.countries_langs))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_hash = reader.read_int()
        _args['hash'] = _val_hash
        _val_countries_langs = reader.tgread_object()
        _args['countries_langs'] = _val_countries_langs
        return cls(**_args)


class PassportConfigNotModified(TLObject):
    """TL type: help.passportConfigNotModified"""
    CONSTRUCTOR_ID = 0xbfb9f457
    SUBCLASS_OF_ID = 0xc666c0ad

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'PassportConfigNotModified',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()


class PeerColorProfileSet(TLObject):
    """TL type: help.peerColorProfileSet"""
    CONSTRUCTOR_ID = 0x767d61eb
    SUBCLASS_OF_ID = 0x11cbe12c

    def __init__(self, palette_colors: List[int], bg_colors: List[int], story_colors: List[int]):
        self.palette_colors = palette_colors
        self.bg_colors = bg_colors
        self.story_colors = story_colors

    def to_dict(self):
        return {
            '_': 'PeerColorProfileSet',
            'palette_colors': self.palette_colors,
            'bg_colors': self.bg_colors,
            'story_colors': self.story_colors,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.palette_colors)))
        for item in self.palette_colors:
            buf.write(struct.pack('<i', item))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.bg_colors)))
        for item in self.bg_colors:
            buf.write(struct.pack('<i', item))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.story_colors)))
        for item in self.story_colors:
            buf.write(struct.pack('<i', item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_palette_colors = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_palette_colors = []
        for _ in range(_count_palette_colors):
            _item_palette_colors = reader.read_int()
            _list_palette_colors.append(_item_palette_colors)
        _args['palette_colors'] = _list_palette_colors
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_bg_colors = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_bg_colors = []
        for _ in range(_count_bg_colors):
            _item_bg_colors = reader.read_int()
            _list_bg_colors.append(_item_bg_colors)
        _args['bg_colors'] = _list_bg_colors
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_story_colors = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_story_colors = []
        for _ in range(_count_story_colors):
            _item_story_colors = reader.read_int()
            _list_story_colors.append(_item_story_colors)
        _args['story_colors'] = _list_story_colors
        return cls(**_args)


class PeerColorSet(TLObject):
    """TL type: help.peerColorSet"""
    CONSTRUCTOR_ID = 0x26219a58
    SUBCLASS_OF_ID = 0x11cbe12c

    def __init__(self, colors: List[int]):
        self.colors = colors

    def to_dict(self):
        return {
            '_': 'PeerColorSet',
            'colors': self.colors,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.colors)))
        for item in self.colors:
            buf.write(struct.pack('<i', item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_colors = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_colors = []
        for _ in range(_count_colors):
            _item_colors = reader.read_int()
            _list_colors.append(_item_colors)
        _args['colors'] = _list_colors
        return cls(**_args)


class PeerColors(TLObject):
    """TL type: help.peerColors"""
    CONSTRUCTOR_ID = 0x00f8ed08
    SUBCLASS_OF_ID = 0x0e3f6733

    def __init__(self, hash: int, colors: List['TypePeerColorOption']):
        self.hash = hash
        self.colors = colors

    def to_dict(self):
        return {
            '_': 'PeerColors',
            'hash': self.hash,
            'colors': self.colors,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', self.hash))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.colors)))
        for item in self.colors:
            buf.write(bytes(item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_hash = reader.read_int()
        _args['hash'] = _val_hash
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_colors = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_colors = []
        for _ in range(_count_colors):
            _item_colors = reader.tgread_object()
            _list_colors.append(_item_colors)
        _args['colors'] = _list_colors
        return cls(**_args)


class PeerColorsNotModified(TLObject):
    """TL type: help.peerColorsNotModified"""
    CONSTRUCTOR_ID = 0x2ba1f5ce
    SUBCLASS_OF_ID = 0x0e3f6733

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'PeerColorsNotModified',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()


class PremiumPromo(TLObject):
    """TL type: help.premiumPromo"""
    CONSTRUCTOR_ID = 0x5334759c
    SUBCLASS_OF_ID = 0xc987a338

    def __init__(self, status_text: str, status_entities: List['TypeMessageEntity'], video_sections: List[str], videos: List['TypeDocument'], period_options: List['TypePremiumSubscriptionOption'], users: List['TypeUser']):
        self.status_text = status_text
        self.status_entities = status_entities
        self.video_sections = video_sections
        self.videos = videos
        self.period_options = period_options
        self.users = users

    def to_dict(self):
        return {
            '_': 'PremiumPromo',
            'status_text': self.status_text,
            'status_entities': self.status_entities,
            'video_sections': self.video_sections,
            'videos': self.videos,
            'period_options': self.period_options,
            'users': self.users,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.status_text))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.status_entities)))
        for item in self.status_entities:
            buf.write(bytes(item))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.video_sections)))
        for item in self.video_sections:
            buf.write(TLObject.serialize_bytes(item))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.videos)))
        for item in self.videos:
            buf.write(bytes(item))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.period_options)))
        for item in self.period_options:
            buf.write(bytes(item))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.users)))
        for item in self.users:
            buf.write(bytes(item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_status_text = reader.tgread_string()
        _args['status_text'] = _val_status_text
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_status_entities = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_status_entities = []
        for _ in range(_count_status_entities):
            _item_status_entities = reader.tgread_object()
            _list_status_entities.append(_item_status_entities)
        _args['status_entities'] = _list_status_entities
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_video_sections = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_video_sections = []
        for _ in range(_count_video_sections):
            _item_video_sections = reader.tgread_string()
            _list_video_sections.append(_item_video_sections)
        _args['video_sections'] = _list_video_sections
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_videos = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_videos = []
        for _ in range(_count_videos):
            _item_videos = reader.tgread_object()
            _list_videos.append(_item_videos)
        _args['videos'] = _list_videos
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_period_options = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_period_options = []
        for _ in range(_count_period_options):
            _item_period_options = reader.tgread_object()
            _list_period_options.append(_item_period_options)
        _args['period_options'] = _list_period_options
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_users = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_users = []
        for _ in range(_count_users):
            _item_users = reader.tgread_object()
            _list_users.append(_item_users)
        _args['users'] = _list_users
        return cls(**_args)


class PromoDataEmpty(TLObject):
    """TL type: help.promoDataEmpty"""
    CONSTRUCTOR_ID = 0x98f6ac75
    SUBCLASS_OF_ID = 0x9d595542

    def __init__(self, expires: Optional[datetime]):
        self.expires = expires

    def to_dict(self):
        return {
            '_': 'PromoDataEmpty',
            'expires': self.expires,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_datetime(self.expires))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_expires = reader.tgread_date()
        _args['expires'] = _val_expires
        return cls(**_args)


class RecentMeUrls(TLObject):
    """TL type: help.recentMeUrls"""
    CONSTRUCTOR_ID = 0x0e0310d7
    SUBCLASS_OF_ID = 0xf269c477

    def __init__(self, urls: List['TypeRecentMeUrl'], chats: List['TypeChat'], users: List['TypeUser']):
        self.urls = urls
        self.chats = chats
        self.users = users

    def to_dict(self):
        return {
            '_': 'RecentMeUrls',
            'urls': self.urls,
            'chats': self.chats,
            'users': self.users,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.urls)))
        for item in self.urls:
            buf.write(bytes(item))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.chats)))
        for item in self.chats:
            buf.write(bytes(item))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.users)))
        for item in self.users:
            buf.write(bytes(item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_urls = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_urls = []
        for _ in range(_count_urls):
            _item_urls = reader.tgread_object()
            _list_urls.append(_item_urls)
        _args['urls'] = _list_urls
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_chats = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_chats = []
        for _ in range(_count_chats):
            _item_chats = reader.tgread_object()
            _list_chats.append(_item_chats)
        _args['chats'] = _list_chats
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_users = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_users = []
        for _ in range(_count_users):
            _item_users = reader.tgread_object()
            _list_users.append(_item_users)
        _args['users'] = _list_users
        return cls(**_args)


class Support(TLObject):
    """TL type: help.support"""
    CONSTRUCTOR_ID = 0x17c6b5f6
    SUBCLASS_OF_ID = 0x7159bceb

    def __init__(self, phone_number: str, user: 'TypeUser'):
        self.phone_number = phone_number
        self.user = user

    def to_dict(self):
        return {
            '_': 'Support',
            'phone_number': self.phone_number,
            'user': self.user,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.phone_number))
        buf.write(bytes(self.user))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_phone_number = reader.tgread_string()
        _args['phone_number'] = _val_phone_number
        _val_user = reader.tgread_object()
        _args['user'] = _val_user
        return cls(**_args)


class SupportName(TLObject):
    """TL type: help.supportName"""
    CONSTRUCTOR_ID = 0x8c05f1c9
    SUBCLASS_OF_ID = 0x7f50b7c2

    def __init__(self, name: str):
        self.name = name

    def to_dict(self):
        return {
            '_': 'SupportName',
            'name': self.name,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.name))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_name = reader.tgread_string()
        _args['name'] = _val_name
        return cls(**_args)


class TermsOfServiceUpdateEmpty(TLObject):
    """TL type: help.termsOfServiceUpdateEmpty"""
    CONSTRUCTOR_ID = 0xe3309f7f
    SUBCLASS_OF_ID = 0x293c2977

    def __init__(self, expires: Optional[datetime]):
        self.expires = expires

    def to_dict(self):
        return {
            '_': 'TermsOfServiceUpdateEmpty',
            'expires': self.expires,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_datetime(self.expires))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_expires = reader.tgread_date()
        _args['expires'] = _val_expires
        return cls(**_args)


class TimezonesList(TLObject):
    """TL type: help.timezonesList"""
    CONSTRUCTOR_ID = 0x7b74ed71
    SUBCLASS_OF_ID = 0xca76e475

    def __init__(self, timezones: List['TypeTimezone'], hash: int):
        self.timezones = timezones
        self.hash = hash

    def to_dict(self):
        return {
            '_': 'TimezonesList',
            'timezones': self.timezones,
            'hash': self.hash,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.timezones)))
        for item in self.timezones:
            buf.write(bytes(item))
        buf.write(struct.pack('<i', self.hash))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_timezones = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_timezones = []
        for _ in range(_count_timezones):
            _item_timezones = reader.tgread_object()
            _list_timezones.append(_item_timezones)
        _args['timezones'] = _list_timezones
        _val_hash = reader.read_int()
        _args['hash'] = _val_hash
        return cls(**_args)


class TimezonesListNotModified(TLObject):
    """TL type: help.timezonesListNotModified"""
    CONSTRUCTOR_ID = 0x970708cc
    SUBCLASS_OF_ID = 0xca76e475

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'TimezonesListNotModified',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()


class UserInfo(TLObject):
    """TL type: help.userInfo"""
    CONSTRUCTOR_ID = 0x01eb3758
    SUBCLASS_OF_ID = 0x5c53d7d8

    def __init__(self, message: str, entities: List['TypeMessageEntity'], author: str, date: Optional[datetime]):
        self.message = message
        self.entities = entities
        self.author = author
        self.date = date

    def to_dict(self):
        return {
            '_': 'UserInfo',
            'message': self.message,
            'entities': self.entities,
            'author': self.author,
            'date': self.date,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.message))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.entities)))
        for item in self.entities:
            buf.write(bytes(item))
        buf.write(TLObject.serialize_bytes(self.author))
        buf.write(TLObject.serialize_datetime(self.date))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_message = reader.tgread_string()
        _args['message'] = _val_message
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_entities = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_entities = []
        for _ in range(_count_entities):
            _item_entities = reader.tgread_object()
            _list_entities.append(_item_entities)
        _args['entities'] = _list_entities
        _val_author = reader.tgread_string()
        _args['author'] = _val_author
        _val_date = reader.tgread_date()
        _args['date'] = _val_date
        return cls(**_args)


class UserInfoEmpty(TLObject):
    """TL type: help.userInfoEmpty"""
    CONSTRUCTOR_ID = 0xf3ae2eed
    SUBCLASS_OF_ID = 0x5c53d7d8

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'UserInfoEmpty',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()

