"""File auto-generated by tglib TL generator. Do not edit manually."""
from ..tlobject import TLObject
from typing import Optional, List, Union
import os
import struct
from datetime import datetime


class Layer223(TLObject):
    """TL type: keyboardbutton.layer.223"""
    CONSTRUCTOR_ID = 0xa2fa4880
    SUBCLASS_OF_ID = 0x0bad74a3

    def __init__(self, text: str):
        self.text = text

    def to_dict(self):
        return {
            '_': 'Layer223',
            'text': self.text,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.text))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_text = reader.tgread_string()
        _args['text'] = _val_text
        return cls(**_args)

