"""File auto-generated by tglib TL generator. Do not edit manually."""
from ..tlobject import TLObject
from typing import Optional, List, Union
import os
import struct
from datetime import datetime


class DifferenceEmpty(TLObject):
    """TL type: updates.differenceEmpty"""
    CONSTRUCTOR_ID = 0x5d75a138
    SUBCLASS_OF_ID = 0x20482874

    def __init__(self, date: Optional[datetime], seq: int):
        self.date = date
        self.seq = seq

    def to_dict(self):
        return {
            '_': 'DifferenceEmpty',
            'date': self.date,
            'seq': self.seq,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_datetime(self.date))
        buf.write(struct.pack('<i', self.seq))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_date = reader.tgread_date()
        _args['date'] = _val_date
        _val_seq = reader.read_int()
        _args['seq'] = _val_seq
        return cls(**_args)


class DifferenceTooLong(TLObject):
    """TL type: updates.differenceTooLong"""
    CONSTRUCTOR_ID = 0x4afe8f6d
    SUBCLASS_OF_ID = 0x20482874

    def __init__(self, pts: int):
        self.pts = pts

    def to_dict(self):
        return {
            '_': 'DifferenceTooLong',
            'pts': self.pts,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', self.pts))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_pts = reader.read_int()
        _args['pts'] = _val_pts
        return cls(**_args)


class State(TLObject):
    """TL type: updates.state"""
    CONSTRUCTOR_ID = 0xa56c2a3e
    SUBCLASS_OF_ID = 0x23df1a01

    def __init__(self, pts: int, qts: int, date: Optional[datetime], seq: int, unread_count: int):
        self.pts = pts
        self.qts = qts
        self.date = date
        self.seq = seq
        self.unread_count = unread_count

    def to_dict(self):
        return {
            '_': 'State',
            'pts': self.pts,
            'qts': self.qts,
            'date': self.date,
            'seq': self.seq,
            'unread_count': self.unread_count,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', self.pts))
        buf.write(struct.pack('<i', self.qts))
        buf.write(TLObject.serialize_datetime(self.date))
        buf.write(struct.pack('<i', self.seq))
        buf.write(struct.pack('<i', self.unread_count))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_pts = reader.read_int()
        _args['pts'] = _val_pts
        _val_qts = reader.read_int()
        _args['qts'] = _val_qts
        _val_date = reader.tgread_date()
        _args['date'] = _val_date
        _val_seq = reader.read_int()
        _args['seq'] = _val_seq
        _val_unread_count = reader.read_int()
        _args['unread_count'] = _val_unread_count
        return cls(**_args)

