"""File auto-generated by tglib TL generator. Do not edit manually."""
from ..tlobject import TLObject
from typing import Optional, List, Union
import os
import struct
from datetime import datetime


class CdnFile(TLObject):
    """TL type: upload.cdnFile"""
    CONSTRUCTOR_ID = 0xa99fca4f
    SUBCLASS_OF_ID = 0xf5ccf928

    def __init__(self, bytes: bytes):
        self.bytes = bytes

    def to_dict(self):
        return {
            '_': 'CdnFile',
            'bytes': self.bytes,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.bytes))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_bytes = reader.tgread_bytes()
        _args['bytes'] = _val_bytes
        return cls(**_args)


class CdnFileReuploadNeeded(TLObject):
    """TL type: upload.cdnFileReuploadNeeded"""
    CONSTRUCTOR_ID = 0xeea8e46e
    SUBCLASS_OF_ID = 0xf5ccf928

    def __init__(self, request_token: bytes):
        self.request_token = request_token

    def to_dict(self):
        return {
            '_': 'CdnFileReuploadNeeded',
            'request_token': self.request_token,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.request_token))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_request_token = reader.tgread_bytes()
        _args['request_token'] = _val_request_token
        return cls(**_args)


class FileCdnRedirect(TLObject):
    """TL type: upload.fileCdnRedirect"""
    CONSTRUCTOR_ID = 0xf18cda44
    SUBCLASS_OF_ID = 0x6c9bd728

    def __init__(self, dc_id: int, file_token: bytes, encryption_key: bytes, encryption_iv: bytes, file_hashes: List['TypeFileHash']):
        self.dc_id = dc_id
        self.file_token = file_token
        self.encryption_key = encryption_key
        self.encryption_iv = encryption_iv
        self.file_hashes = file_hashes

    def to_dict(self):
        return {
            '_': 'FileCdnRedirect',
            'dc_id': self.dc_id,
            'file_token': self.file_token,
            'encryption_key': self.encryption_key,
            'encryption_iv': self.encryption_iv,
            'file_hashes': self.file_hashes,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', self.dc_id))
        buf.write(TLObject.serialize_bytes(self.file_token))
        buf.write(TLObject.serialize_bytes(self.encryption_key))
        buf.write(TLObject.serialize_bytes(self.encryption_iv))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.file_hashes)))
        for item in self.file_hashes:
            buf.write(bytes(item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_dc_id = reader.read_int()
        _args['dc_id'] = _val_dc_id
        _val_file_token = reader.tgread_bytes()
        _args['file_token'] = _val_file_token
        _val_encryption_key = reader.tgread_bytes()
        _args['encryption_key'] = _val_encryption_key
        _val_encryption_iv = reader.tgread_bytes()
        _args['encryption_iv'] = _val_encryption_iv
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_file_hashes = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_file_hashes = []
        for _ in range(_count_file_hashes):
            _item_file_hashes = reader.tgread_object()
            _list_file_hashes.append(_item_file_hashes)
        _args['file_hashes'] = _list_file_hashes
        return cls(**_args)

