"""File auto-generated by tglib TL generator. Do not edit manually."""
from ..tlobject import TLObject
from ..tlobject import TLRequest
from typing import Optional, List, Union
import os
import struct
from datetime import datetime


class ApplyGiftCodeRequest(TLRequest):
    """TL type: payments.applyGiftCode"""
    CONSTRUCTOR_ID = 0xf6e26854
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, slug: str):
        self.slug = slug

    def to_dict(self):
        return {
            '_': 'ApplyGiftCodeRequest',
            'slug': self.slug,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.slug))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_slug = reader.tgread_string()
        _args['slug'] = _val_slug
        return cls(**_args)


class AssignAppStoreTransactionRequest(TLRequest):
    """TL type: payments.assignAppStoreTransaction"""
    CONSTRUCTOR_ID = 0x80ed747d
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, receipt: bytes, purpose: 'TypeInputStorePaymentPurpose'):
        self.receipt = receipt
        self.purpose = purpose

    def to_dict(self):
        return {
            '_': 'AssignAppStoreTransactionRequest',
            'receipt': self.receipt,
            'purpose': self.purpose,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.receipt))
        buf.write(bytes(self.purpose))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_receipt = reader.tgread_bytes()
        _args['receipt'] = _val_receipt
        _val_purpose = reader.tgread_object()
        _args['purpose'] = _val_purpose
        return cls(**_args)


class AssignPlayMarketTransactionRequest(TLRequest):
    """TL type: payments.assignPlayMarketTransaction"""
    CONSTRUCTOR_ID = 0xdffd50d3
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, receipt: 'TypeDataJSON', purpose: 'TypeInputStorePaymentPurpose'):
        self.receipt = receipt
        self.purpose = purpose

    def to_dict(self):
        return {
            '_': 'AssignPlayMarketTransactionRequest',
            'receipt': self.receipt,
            'purpose': self.purpose,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.receipt))
        buf.write(bytes(self.purpose))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_receipt = reader.tgread_object()
        _args['receipt'] = _val_receipt
        _val_purpose = reader.tgread_object()
        _args['purpose'] = _val_purpose
        return cls(**_args)


class CanPurchaseStoreRequest(TLRequest):
    """TL type: payments.canPurchaseStore"""
    CONSTRUCTOR_ID = 0x4fdc5ea7
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, purpose: 'TypeInputStorePaymentPurpose'):
        self.purpose = purpose

    def to_dict(self):
        return {
            '_': 'CanPurchaseStoreRequest',
            'purpose': self.purpose,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.purpose))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_purpose = reader.tgread_object()
        _args['purpose'] = _val_purpose
        return cls(**_args)


class CheckCanSendGiftRequest(TLRequest):
    """TL type: payments.checkCanSendGift"""
    CONSTRUCTOR_ID = 0xc0c4edc9
    SUBCLASS_OF_ID = 0x632efa30

    def __init__(self, gift_id: int):
        self.gift_id = gift_id

    def to_dict(self):
        return {
            '_': 'CheckCanSendGiftRequest',
            'gift_id': self.gift_id,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<q', self.gift_id))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_gift_id = reader.read_long()
        _args['gift_id'] = _val_gift_id
        return cls(**_args)


class CheckGiftCodeRequest(TLRequest):
    """TL type: payments.checkGiftCode"""
    CONSTRUCTOR_ID = 0x8e51b4c1
    SUBCLASS_OF_ID = 0x5b2997e8

    def __init__(self, slug: str):
        self.slug = slug

    def to_dict(self):
        return {
            '_': 'CheckGiftCodeRequest',
            'slug': self.slug,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.slug))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_slug = reader.tgread_string()
        _args['slug'] = _val_slug
        return cls(**_args)


class ConnectStarRefBotRequest(TLRequest):
    """TL type: payments.connectStarRefBot"""
    CONSTRUCTOR_ID = 0x7ed5348a
    SUBCLASS_OF_ID = 0x235e1a67

    def __init__(self, peer: 'TypeInputPeer', bot: 'TypeInputUser'):
        self.peer = peer
        self.bot = bot

    def to_dict(self):
        return {
            '_': 'ConnectStarRefBotRequest',
            'peer': self.peer,
            'bot': self.bot,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(bytes(self.bot))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _val_bot = reader.tgread_object()
        _args['bot'] = _val_bot
        return cls(**_args)


class ConvertStarGiftRequest(TLRequest):
    """TL type: payments.convertStarGift"""
    CONSTRUCTOR_ID = 0x74bf076b
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, stargift: 'TypeInputSavedStarGift'):
        self.stargift = stargift

    def to_dict(self):
        return {
            '_': 'ConvertStarGiftRequest',
            'stargift': self.stargift,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.stargift))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_stargift = reader.tgread_object()
        _args['stargift'] = _val_stargift
        return cls(**_args)


class CraftStarGiftRequest(TLRequest):
    """TL type: payments.craftStarGift"""
    CONSTRUCTOR_ID = 0xb0f9684f
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, stargift: List['TypeInputSavedStarGift']):
        self.stargift = stargift

    def to_dict(self):
        return {
            '_': 'CraftStarGiftRequest',
            'stargift': self.stargift,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.stargift)))
        for item in self.stargift:
            buf.write(bytes(item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_stargift = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_stargift = []
        for _ in range(_count_stargift):
            _item_stargift = reader.tgread_object()
            _list_stargift.append(_item_stargift)
        _args['stargift'] = _list_stargift
        return cls(**_args)


class CreateStarGiftCollectionRequest(TLRequest):
    """TL type: payments.createStarGiftCollection"""
    CONSTRUCTOR_ID = 0x1f4a0e87
    SUBCLASS_OF_ID = 0x43e0cb4a

    def __init__(self, peer: 'TypeInputPeer', title: str, stargift: List['TypeInputSavedStarGift']):
        self.peer = peer
        self.title = title
        self.stargift = stargift

    def to_dict(self):
        return {
            '_': 'CreateStarGiftCollectionRequest',
            'peer': self.peer,
            'title': self.title,
            'stargift': self.stargift,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(TLObject.serialize_bytes(self.title))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.stargift)))
        for item in self.stargift:
            buf.write(bytes(item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _val_title = reader.tgread_string()
        _args['title'] = _val_title
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_stargift = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_stargift = []
        for _ in range(_count_stargift):
            _item_stargift = reader.tgread_object()
            _list_stargift.append(_item_stargift)
        _args['stargift'] = _list_stargift
        return cls(**_args)


class DeleteStarGiftCollectionRequest(TLRequest):
    """TL type: payments.deleteStarGiftCollection"""
    CONSTRUCTOR_ID = 0xad5648e8
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, peer: 'TypeInputPeer', collection_id: int):
        self.peer = peer
        self.collection_id = collection_id

    def to_dict(self):
        return {
            '_': 'DeleteStarGiftCollectionRequest',
            'peer': self.peer,
            'collection_id': self.collection_id,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(struct.pack('<i', self.collection_id))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _val_collection_id = reader.read_int()
        _args['collection_id'] = _val_collection_id
        return cls(**_args)


class ExportInvoiceRequest(TLRequest):
    """TL type: payments.exportInvoice"""
    CONSTRUCTOR_ID = 0x0f91b065
    SUBCLASS_OF_ID = 0x36105432

    def __init__(self, invoice_media: 'TypeInputMedia'):
        self.invoice_media = invoice_media

    def to_dict(self):
        return {
            '_': 'ExportInvoiceRequest',
            'invoice_media': self.invoice_media,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.invoice_media))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_invoice_media = reader.tgread_object()
        _args['invoice_media'] = _val_invoice_media
        return cls(**_args)


class FulfillStarsSubscriptionRequest(TLRequest):
    """TL type: payments.fulfillStarsSubscription"""
    CONSTRUCTOR_ID = 0xcc5bebb3
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, peer: 'TypeInputPeer', subscription_id: str):
        self.peer = peer
        self.subscription_id = subscription_id

    def to_dict(self):
        return {
            '_': 'FulfillStarsSubscriptionRequest',
            'peer': self.peer,
            'subscription_id': self.subscription_id,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(TLObject.serialize_bytes(self.subscription_id))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _val_subscription_id = reader.tgread_string()
        _args['subscription_id'] = _val_subscription_id
        return cls(**_args)


class GetBankCardDataRequest(TLRequest):
    """TL type: payments.getBankCardData"""
    CONSTRUCTOR_ID = 0x2e79d779
    SUBCLASS_OF_ID = 0x8c6dd68b

    def __init__(self, number: str):
        self.number = number

    def to_dict(self):
        return {
            '_': 'GetBankCardDataRequest',
            'number': self.number,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.number))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_number = reader.tgread_string()
        _args['number'] = _val_number
        return cls(**_args)


class GetConnectedStarRefBotRequest(TLRequest):
    """TL type: payments.getConnectedStarRefBot"""
    CONSTRUCTOR_ID = 0xb7d998f0
    SUBCLASS_OF_ID = 0x235e1a67

    def __init__(self, peer: 'TypeInputPeer', bot: 'TypeInputUser'):
        self.peer = peer
        self.bot = bot

    def to_dict(self):
        return {
            '_': 'GetConnectedStarRefBotRequest',
            'peer': self.peer,
            'bot': self.bot,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(bytes(self.bot))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _val_bot = reader.tgread_object()
        _args['bot'] = _val_bot
        return cls(**_args)


class GetCraftStarGiftsRequest(TLRequest):
    """TL type: payments.getCraftStarGifts"""
    CONSTRUCTOR_ID = 0xfd05dd00
    SUBCLASS_OF_ID = 0xd5112897

    def __init__(self, gift_id: int, offset: str, limit: int):
        self.gift_id = gift_id
        self.offset = offset
        self.limit = limit

    def to_dict(self):
        return {
            '_': 'GetCraftStarGiftsRequest',
            'gift_id': self.gift_id,
            'offset': self.offset,
            'limit': self.limit,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<q', self.gift_id))
        buf.write(TLObject.serialize_bytes(self.offset))
        buf.write(struct.pack('<i', self.limit))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_gift_id = reader.read_long()
        _args['gift_id'] = _val_gift_id
        _val_offset = reader.tgread_string()
        _args['offset'] = _val_offset
        _val_limit = reader.read_int()
        _args['limit'] = _val_limit
        return cls(**_args)


class GetGiveawayInfoRequest(TLRequest):
    """TL type: payments.getGiveawayInfo"""
    CONSTRUCTOR_ID = 0xf4239425
    SUBCLASS_OF_ID = 0x96a377bd

    def __init__(self, peer: 'TypeInputPeer', msg_id: int):
        self.peer = peer
        self.msg_id = msg_id

    def to_dict(self):
        return {
            '_': 'GetGiveawayInfoRequest',
            'peer': self.peer,
            'msg_id': self.msg_id,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(struct.pack('<i', self.msg_id))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _val_msg_id = reader.read_int()
        _args['msg_id'] = _val_msg_id
        return cls(**_args)


class GetPaymentReceiptRequest(TLRequest):
    """TL type: payments.getPaymentReceipt"""
    CONSTRUCTOR_ID = 0x2478d1cc
    SUBCLASS_OF_ID = 0x590093c9

    def __init__(self, peer: 'TypeInputPeer', msg_id: int):
        self.peer = peer
        self.msg_id = msg_id

    def to_dict(self):
        return {
            '_': 'GetPaymentReceiptRequest',
            'peer': self.peer,
            'msg_id': self.msg_id,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(struct.pack('<i', self.msg_id))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _val_msg_id = reader.read_int()
        _args['msg_id'] = _val_msg_id
        return cls(**_args)


class GetSavedInfoRequest(TLRequest):
    """TL type: payments.getSavedInfo"""
    CONSTRUCTOR_ID = 0x227d824b
    SUBCLASS_OF_ID = 0xad3cf146

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'GetSavedInfoRequest',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()


class GetSavedStarGiftRequest(TLRequest):
    """TL type: payments.getSavedStarGift"""
    CONSTRUCTOR_ID = 0xb455a106
    SUBCLASS_OF_ID = 0xd5112897

    def __init__(self, stargift: List['TypeInputSavedStarGift']):
        self.stargift = stargift

    def to_dict(self):
        return {
            '_': 'GetSavedStarGiftRequest',
            'stargift': self.stargift,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.stargift)))
        for item in self.stargift:
            buf.write(bytes(item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_stargift = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_stargift = []
        for _ in range(_count_stargift):
            _item_stargift = reader.tgread_object()
            _list_stargift.append(_item_stargift)
        _args['stargift'] = _list_stargift
        return cls(**_args)


class GetStarGiftActiveAuctionsRequest(TLRequest):
    """TL type: payments.getStarGiftActiveAuctions"""
    CONSTRUCTOR_ID = 0xa5d0514d
    SUBCLASS_OF_ID = 0x917dd0c7

    def __init__(self, hash: int):
        self.hash = hash

    def to_dict(self):
        return {
            '_': 'GetStarGiftActiveAuctionsRequest',
            'hash': self.hash,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<q', self.hash))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_hash = reader.read_long()
        _args['hash'] = _val_hash
        return cls(**_args)


class GetStarGiftAuctionAcquiredGiftsRequest(TLRequest):
    """TL type: payments.getStarGiftAuctionAcquiredGifts"""
    CONSTRUCTOR_ID = 0x6ba2cbec
    SUBCLASS_OF_ID = 0xa7080a1b

    def __init__(self, gift_id: int):
        self.gift_id = gift_id

    def to_dict(self):
        return {
            '_': 'GetStarGiftAuctionAcquiredGiftsRequest',
            'gift_id': self.gift_id,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<q', self.gift_id))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_gift_id = reader.read_long()
        _args['gift_id'] = _val_gift_id
        return cls(**_args)


class GetStarGiftAuctionStateRequest(TLRequest):
    """TL type: payments.getStarGiftAuctionState"""
    CONSTRUCTOR_ID = 0x5c9ff4d6
    SUBCLASS_OF_ID = 0x1a318599

    def __init__(self, auction: 'TypeInputStarGiftAuction', version: int):
        self.auction = auction
        self.version = version

    def to_dict(self):
        return {
            '_': 'GetStarGiftAuctionStateRequest',
            'auction': self.auction,
            'version': self.version,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.auction))
        buf.write(struct.pack('<i', self.version))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_auction = reader.tgread_object()
        _args['auction'] = _val_auction
        _val_version = reader.read_int()
        _args['version'] = _val_version
        return cls(**_args)


class GetStarGiftCollectionsRequest(TLRequest):
    """TL type: payments.getStarGiftCollections"""
    CONSTRUCTOR_ID = 0x981b91dd
    SUBCLASS_OF_ID = 0xf01721ec

    def __init__(self, peer: 'TypeInputPeer', hash: int):
        self.peer = peer
        self.hash = hash

    def to_dict(self):
        return {
            '_': 'GetStarGiftCollectionsRequest',
            'peer': self.peer,
            'hash': self.hash,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(struct.pack('<q', self.hash))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _val_hash = reader.read_long()
        _args['hash'] = _val_hash
        return cls(**_args)


class GetStarGiftUpgradeAttributesRequest(TLRequest):
    """TL type: payments.getStarGiftUpgradeAttributes"""
    CONSTRUCTOR_ID = 0x6d038b58
    SUBCLASS_OF_ID = 0x0f46acef

    def __init__(self, gift_id: int):
        self.gift_id = gift_id

    def to_dict(self):
        return {
            '_': 'GetStarGiftUpgradeAttributesRequest',
            'gift_id': self.gift_id,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<q', self.gift_id))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_gift_id = reader.read_long()
        _args['gift_id'] = _val_gift_id
        return cls(**_args)


class GetStarGiftUpgradePreviewRequest(TLRequest):
    """TL type: payments.getStarGiftUpgradePreview"""
    CONSTRUCTOR_ID = 0x9c9abcb1
    SUBCLASS_OF_ID = 0x5e2b68c7

    def __init__(self, gift_id: int):
        self.gift_id = gift_id

    def to_dict(self):
        return {
            '_': 'GetStarGiftUpgradePreviewRequest',
            'gift_id': self.gift_id,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<q', self.gift_id))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_gift_id = reader.read_long()
        _args['gift_id'] = _val_gift_id
        return cls(**_args)


class GetStarGiftWithdrawalUrlRequest(TLRequest):
    """TL type: payments.getStarGiftWithdrawalUrl"""
    CONSTRUCTOR_ID = 0xd06e93a8
    SUBCLASS_OF_ID = 0xa2822dc5

    def __init__(self, stargift: 'TypeInputSavedStarGift', password: 'TypeInputCheckPasswordSRP'):
        self.stargift = stargift
        self.password = password

    def to_dict(self):
        return {
            '_': 'GetStarGiftWithdrawalUrlRequest',
            'stargift': self.stargift,
            'password': self.password,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.stargift))
        buf.write(bytes(self.password))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_stargift = reader.tgread_object()
        _args['stargift'] = _val_stargift
        _val_password = reader.tgread_object()
        _args['password'] = _val_password
        return cls(**_args)


class GetStarGiftsRequest(TLRequest):
    """TL type: payments.getStarGifts"""
    CONSTRUCTOR_ID = 0xc4563590
    SUBCLASS_OF_ID = 0x6178d9a4

    def __init__(self, hash: int):
        self.hash = hash

    def to_dict(self):
        return {
            '_': 'GetStarGiftsRequest',
            'hash': self.hash,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<i', self.hash))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_hash = reader.read_int()
        _args['hash'] = _val_hash
        return cls(**_args)


class GetStarsGiveawayOptionsRequest(TLRequest):
    """TL type: payments.getStarsGiveawayOptions"""
    CONSTRUCTOR_ID = 0xbd1efd3e
    SUBCLASS_OF_ID = 0xf8db30a9

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'GetStarsGiveawayOptionsRequest',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()


class GetStarsRevenueAdsAccountUrlRequest(TLRequest):
    """TL type: payments.getStarsRevenueAdsAccountUrl"""
    CONSTRUCTOR_ID = 0xd1d7efc5
    SUBCLASS_OF_ID = 0x4a228b15

    def __init__(self, peer: 'TypeInputPeer'):
        self.peer = peer

    def to_dict(self):
        return {
            '_': 'GetStarsRevenueAdsAccountUrlRequest',
            'peer': self.peer,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        return cls(**_args)


class GetStarsTopupOptionsRequest(TLRequest):
    """TL type: payments.getStarsTopupOptions"""
    CONSTRUCTOR_ID = 0xc00ec7d3
    SUBCLASS_OF_ID = 0xd4fe8a99

    def __init__(self):
        pass

    def to_dict(self):
        return {
            '_': 'GetStarsTopupOptionsRequest',
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        return cls()


class GetUniqueStarGiftRequest(TLRequest):
    """TL type: payments.getUniqueStarGift"""
    CONSTRUCTOR_ID = 0xa1974d72
    SUBCLASS_OF_ID = 0x78b0c5fb

    def __init__(self, slug: str):
        self.slug = slug

    def to_dict(self):
        return {
            '_': 'GetUniqueStarGiftRequest',
            'slug': self.slug,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.slug))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_slug = reader.tgread_string()
        _args['slug'] = _val_slug
        return cls(**_args)


class GetUniqueStarGiftValueInfoRequest(TLRequest):
    """TL type: payments.getUniqueStarGiftValueInfo"""
    CONSTRUCTOR_ID = 0x4365af6b
    SUBCLASS_OF_ID = 0x16355bc4

    def __init__(self, slug: str):
        self.slug = slug

    def to_dict(self):
        return {
            '_': 'GetUniqueStarGiftValueInfoRequest',
            'slug': self.slug,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(TLObject.serialize_bytes(self.slug))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_slug = reader.tgread_string()
        _args['slug'] = _val_slug
        return cls(**_args)


class LaunchPrepaidGiveawayRequest(TLRequest):
    """TL type: payments.launchPrepaidGiveaway"""
    CONSTRUCTOR_ID = 0x5ff58f20
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, peer: 'TypeInputPeer', giveaway_id: int, purpose: 'TypeInputStorePaymentPurpose'):
        self.peer = peer
        self.giveaway_id = giveaway_id
        self.purpose = purpose

    def to_dict(self):
        return {
            '_': 'LaunchPrepaidGiveawayRequest',
            'peer': self.peer,
            'giveaway_id': self.giveaway_id,
            'purpose': self.purpose,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(struct.pack('<q', self.giveaway_id))
        buf.write(bytes(self.purpose))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _val_giveaway_id = reader.read_long()
        _args['giveaway_id'] = _val_giveaway_id
        _val_purpose = reader.tgread_object()
        _args['purpose'] = _val_purpose
        return cls(**_args)


class RefundStarsChargeRequest(TLRequest):
    """TL type: payments.refundStarsCharge"""
    CONSTRUCTOR_ID = 0x25ae8f4a
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, user_id: 'TypeInputUser', charge_id: str):
        self.user_id = user_id
        self.charge_id = charge_id

    def to_dict(self):
        return {
            '_': 'RefundStarsChargeRequest',
            'user_id': self.user_id,
            'charge_id': self.charge_id,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.user_id))
        buf.write(TLObject.serialize_bytes(self.charge_id))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_user_id = reader.tgread_object()
        _args['user_id'] = _val_user_id
        _val_charge_id = reader.tgread_string()
        _args['charge_id'] = _val_charge_id
        return cls(**_args)


class ReorderStarGiftCollectionsRequest(TLRequest):
    """TL type: payments.reorderStarGiftCollections"""
    CONSTRUCTOR_ID = 0xc32af4cc
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, peer: 'TypeInputPeer', order: List[int]):
        self.peer = peer
        self.order = order

    def to_dict(self):
        return {
            '_': 'ReorderStarGiftCollectionsRequest',
            'peer': self.peer,
            'order': self.order,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.order)))
        for item in self.order:
            buf.write(struct.pack('<i', item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_order = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_order = []
        for _ in range(_count_order):
            _item_order = reader.read_int()
            _list_order.append(_item_order)
        _args['order'] = _list_order
        return cls(**_args)


class RequestRecurringPaymentRequest(TLRequest):
    """TL type: payments.requestRecurringPayment"""
    CONSTRUCTOR_ID = 0x146e958d
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, user_id: 'TypeInputUser', recurring_init_charge: str, invoice_media: 'TypeInputMedia'):
        self.user_id = user_id
        self.recurring_init_charge = recurring_init_charge
        self.invoice_media = invoice_media

    def to_dict(self):
        return {
            '_': 'RequestRecurringPaymentRequest',
            'user_id': self.user_id,
            'recurring_init_charge': self.recurring_init_charge,
            'invoice_media': self.invoice_media,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.user_id))
        buf.write(TLObject.serialize_bytes(self.recurring_init_charge))
        buf.write(bytes(self.invoice_media))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_user_id = reader.tgread_object()
        _args['user_id'] = _val_user_id
        _val_recurring_init_charge = reader.tgread_string()
        _args['recurring_init_charge'] = _val_recurring_init_charge
        _val_invoice_media = reader.tgread_object()
        _args['invoice_media'] = _val_invoice_media
        return cls(**_args)


class SendStarsFormRequest(TLRequest):
    """TL type: payments.sendStarsForm"""
    CONSTRUCTOR_ID = 0x7998c914
    SUBCLASS_OF_ID = 0x8ae16a9d

    def __init__(self, form_id: int, invoice: 'TypeInputInvoice'):
        self.form_id = form_id
        self.invoice = invoice

    def to_dict(self):
        return {
            '_': 'SendStarsFormRequest',
            'form_id': self.form_id,
            'invoice': self.invoice,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(struct.pack('<q', self.form_id))
        buf.write(bytes(self.invoice))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_form_id = reader.read_long()
        _args['form_id'] = _val_form_id
        _val_invoice = reader.tgread_object()
        _args['invoice'] = _val_invoice
        return cls(**_args)


class ToggleStarGiftsPinnedToTopRequest(TLRequest):
    """TL type: payments.toggleStarGiftsPinnedToTop"""
    CONSTRUCTOR_ID = 0x1513e7b0
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, peer: 'TypeInputPeer', stargift: List['TypeInputSavedStarGift']):
        self.peer = peer
        self.stargift = stargift

    def to_dict(self):
        return {
            '_': 'ToggleStarGiftsPinnedToTopRequest',
            'peer': self.peer,
            'stargift': self.stargift,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.peer))
        buf.write(struct.pack('<i', 0x1cb5c415))  # vector id
        buf.write(struct.pack('<i', len(self.stargift)))
        for item in self.stargift:
            buf.write(bytes(item))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_peer = reader.tgread_object()
        _args['peer'] = _val_peer
        _vec_id = reader.read_int(signed=False)
        if _vec_id != 0x1cb5c415:
            raise RuntimeError(f'Expected vector but got 0x{_vec_id:08x}')
        _count_stargift = reader.read_int(signed=False)  # BUG6 fix: unsigned count
        _list_stargift = []
        for _ in range(_count_stargift):
            _item_stargift = reader.tgread_object()
            _list_stargift.append(_item_stargift)
        _args['stargift'] = _list_stargift
        return cls(**_args)


class TransferStarGiftRequest(TLRequest):
    """TL type: payments.transferStarGift"""
    CONSTRUCTOR_ID = 0x7f18176a
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, stargift: 'TypeInputSavedStarGift', to_id: 'TypeInputPeer'):
        self.stargift = stargift
        self.to_id = to_id

    def to_dict(self):
        return {
            '_': 'TransferStarGiftRequest',
            'stargift': self.stargift,
            'to_id': self.to_id,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.stargift))
        buf.write(bytes(self.to_id))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_stargift = reader.tgread_object()
        _args['stargift'] = _val_stargift
        _val_to_id = reader.tgread_object()
        _args['to_id'] = _val_to_id
        return cls(**_args)


class UpdateStarGiftPriceRequest(TLRequest):
    """TL type: payments.updateStarGiftPrice"""
    CONSTRUCTOR_ID = 0xedbe6ccb
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, stargift: 'TypeInputSavedStarGift', resell_amount: 'TypeStarsAmount'):
        self.stargift = stargift
        self.resell_amount = resell_amount

    def to_dict(self):
        return {
            '_': 'UpdateStarGiftPriceRequest',
            'stargift': self.stargift,
            'resell_amount': self.resell_amount,
        }

    def _bytes(self) -> bytes:
        import io
        buf = io.BytesIO()
        buf.write(struct.pack('<I', self.CONSTRUCTOR_ID))
        buf.write(bytes(self.stargift))
        buf.write(bytes(self.resell_amount))
        return buf.getvalue()

    @classmethod
    def from_reader(cls, reader):
        _args = {}
        _val_stargift = reader.tgread_object()
        _args['stargift'] = _val_stargift
        _val_resell_amount = reader.tgread_object()
        _args['resell_amount'] = _val_resell_amount
        return cls(**_args)

